8 Create event
bprof-projm/wman pull request #35
Opened 2021-10-10 17:31 UTC by akosgdcsi

-Data entities and connections changed accordingly ER_diagram

-refactoring for logout had to be done in order to identityuser's id to be int

-automapper added for converting DTO's to data entities 

-repositories for each entities created for backend work to be done simultaneously 

-create event logic and controller created for the issue

2021-10-10 17:48 UTC, rolandbogdan requested changes
PLEASE ÁKOS STOP REQUESTING MY REVIEWS ON YOUR PULL REQUESTS

2021-10-10 17:50 UTC, tubamark98 commented
Bence do your part already.

2021-10-10 17:57 UTC, rolandbogdan requested changes
Make it better

2021-10-10 17:57 UTC, rolandbogdan commented on wman-backend/Wman.Data/wmanDb.cs
> +
Remove several consecutive empty lines

2021-10-10 17:57 UTC, rolandbogdan commented on wman-backend/Wman.Logic/Helpers/AutoMapperProfiles.cs
> +    // chose the destination-property and map the source itself
Fix identation of comment. Start comment with capital letter, and use correct grammar

2021-10-10 17:58 UTC, akosgdcsi commented on wman-backend/Wman.Data/wmanDb.cs
> +
right on chief 🤙🏻

2021-10-10 17:59 UTC, tubamark98 commented on wman-backend/Wman.Logic/Helpers/AutoMapperProfiles.cs
> +    // chose the destination-property and map the source itself
Very cool and all but i don't remember asking

2021-10-10 17:59 UTC, akosgdcsi commented on wman-backend/Wman.Logic/Helpers/AutoMapperProfiles.cs
> +    // chose the destination-property and map the source itself
I dare to say no 🚳 ⛔

2021-10-10 22:28 UTC, tsaskater commented on wman-backend/Wman.Logic/Helpers/AutoMapperProfiles.cs
> +    // chose the destination-property and map the source itself
Please go to your own project->[here](https://shorturl.at/pqzEZ)

2021-10-12 15:02 UTC, luxz97 approved these changes

2021-10-12 22:44 UTC, pop-simon approved these changes

2021-10-13 07:29 UTC, tsaskater approved these changes
Good Job!
@akosgdcsi @luxz97 both of you did good.😎😉

2021-10-13 07:35 UTC, merged