14 Create labels and use them to events
bprof-projm/wman pull request #43
Opened 2021-11-01 18:07 UTC by akosgdcsi

we should label our authism

2021-11-01 19:25 UTC, tsaskater requested changes

2021-11-01 19:25 UTC, tsaskater commented on wman-backend/Wman.Logic/Classes/LabelLogic.cs
> +        public async Task UpdateLabel(int Id, CreateLabelDTO NewLabel)
The result can be null, please validate it.
If the requested doesn't exist, we should return a 404 not found. 
That should be solved in the upcoming issue. For the moment u can use argument exception for that as you did at many other places.
Besides this issue, everything seems to be working well. Good job!

2021-11-01 20:10 UTC, tsaskater approved these changes
Good Job!

2021-11-01 20:45 UTC, pop-simon approved these changes
Looks good, keep it up! 🏆

***Normally you should have extended the `GetAllWorkEvent()` method with including `Label`, but as I saw there is already an issue for that.***

2021-11-02 10:45 UTC, luxz97 approved these changes

2021-11-02 11:16 UTC, merged