40 Provide an endpoint which contains all the data to display an event's details
bprof-projm/wman pull request #45
Opened 2021-11-07 13:58 UTC by akosgdcsi

photo storage implemented and BIG endpoint created

in order to test this method you first have to update the appsettings.json file.

2021-11-07 19:01 UTC, tsaskater requested changes
Minor changes needed. Please update the Photo endpoint to include the term "profilePicture". Please change the PhotoLogic to rely on the user's id rather then the PublicId.

2021-11-07 19:01 UTC, tsaskater commented on wman-backend/Wman.WebAPI/Controllers/PhotoController.cs
> +        [HttpPost("AddPhoto/{userName}")]
The method name should be AddProfilePhoto as it was intended to do that.

2021-11-07 19:01 UTC, tsaskater commented on wman-backend/Wman.WebAPI/Controllers/PhotoController.cs
> +        public async Task<ActionResult<PhotoDTO>> UpdateProfilePhoto(string publicId, IFormFile file)
Same applies here.

2021-11-07 19:01 UTC, tsaskater commented on wman-backend/Wman.WebAPI/Controllers/PhotoController.cs
> +        [HttpDelete("RemovePhoto/{publicId}")]
Same applies here.

2021-11-07 19:01 UTC, tsaskater commented on wman-backend/Wman.Logic/Classes/PhotoLogic.cs
> +        public async Task<PhotoDTO> UpdateProfilePhoto(string publicId, IFormFile file)
Don't rely on the publicphotoId because it's an unnecessary dependency.
Instead use the user's id to update their profile picture.

2021-11-07 19:01 UTC, tsaskater commented on wman-backend/Wman.Logic/Classes/PhotoLogic.cs
> +        public async Task RemoveProfilePhoto(string publicId)
Don't rely on the publicphotoId because it's an unnecessary dependency.
Instead use the user's id to remove their profile picture.

2021-11-07 22:52 UTC, tsaskater approved these changes
Nice work!🕵️‍♂️

2021-11-08 00:18 UTC, luxz97 approved these changes

2021-11-08 21:56 UTC, pop-simon requested changes
Consider doing the following
--

- Delete the `WorkCardUserDTO` because it is not used anywhere
- Delete the `TimeSpan WorkTime` for all occurance (entities, DTO models etc.) because it is not needed (it was my idea to use it in order to use the DB instead of CPU resources but the implementation does not use it so it is unneccesary)
- Furthermore the `/Event/all`, `/GetEvent/{id}`, `/Event/users` endpoints are not needed anymore in my opinion. If I recall correctly to the project description the BE should never return every workevent or a single event by ID. Thanks to this issue the `CalendarEvent` related endpoints response contains the users of each event therefore the `Event/users` is no longer needed.

Besides these it is a very good job! 🛸

2021-11-08 21:56 UTC, pop-simon commented on wman-backend/Wman.Repository/Classes/WorkEventRepo.cs
> +            return this.db.WorkEvent.AsNoTracking().Include(x => x.Address).Include(x => x.AssignedUsers).ThenInclude(x => x.ProfilePicture).Include(x => x.Labels);
As you would like to return every `WorkEvent` ordered by its `EstimatedStartDate` at `CalendarEventLogic` I would suggest the following solution instead of appending `.OrderBy(x => x.EstimatedStartDate)` to every query in `CalendarEventLogic`.
```suggestion
            return this.db.WorkEvent.AsNoTracking().Include(x => x.Address).Include(x => x.AssignedUsers).ThenInclude(x => x.ProfilePicture).Include(x => x.Labels).OrderBy(x => x.EstimatedStartDate);
```

2021-11-09 08:46 UTC, pop-simon approved these changes
Good job 👏

2021-11-09 09:24 UTC, merged