Feature/19 create user group roles
bprof-projm/wman pull request #46
Opened 2021-11-07 18:04 UTC by luxz97

2021-11-08 00:37 UTC, tsaskater requested changes
A lot of changes needed.
As I said before we require doing this:
> Modify the logic accordingly.
> (For example a manager should not be able to assign users from the role Admin, Manager.)

Updated to issue to contain this part, but we spoke about this before... This is the main reason why this has the estimate of 8.

Please read through the endpoints AND the logic with the questions:
- Who should be able to use it?
- Which user does it apply to? (Same as you did with the worker's workload. Check for particular role.)

The term "user" is just an entity in our app. What separates them logically are the roles which they are assigned to. This is the goal of this refactor. 
Furthermore, please check the labels assigned to this issue, Epic 1 & Refactor.
Setting a role is Epic 3, [this issue](https://github.com/bprof-projm/wman/issues/28).
(I'm sure it's good for debugging, but seeding serves the same purpose... For the moment it's okay to have it here,  just an FYI)
Userroles is just wrong, we do not plan having multiple roles for one user, and JWT HAS the same data, we do not need an endpoint for this as we said this same thing before.
role/members is also epic 3 this is an admin task related endpoint.
(useless here unless you are testing setting a role which is also epic 3)
If you are interested in the data you can just use the built-in SSOE.

2021-11-08 01:18 UTC, luxz97 commented
>Modify the logic accordingly.
(For example a manager should not be able to assign users from the role Admin, Manager.)

>Please read through the endpoints AND the logic with the questions: (....)

I did look through the logic, with this in mind. For the example you mentioned, I even provided an implementation, which I then commented out, because I did see some reason behind sometimes wanting to assing a user to an event, who isn't member of the worker role. Furthermore, every endpoint was evaluated, on who should be able accessing it. 

`//if (await userManager.IsInRoleAsync(selectedUser, "Worker") == false)
            //{
            //    throw new InvalidOperationException("Selected user does not have the provided role.");
            //}`
line 42 of EventLogic.cs (Similar with massassign)

Now if you still demand this, I can uncomment it for you, but do you have any specifics besides this, where I wasn't thorough enough, in looking through the code? Workload calc by usernames was not covered, but that was on purpose too. Usernames submitted there had to be sent for a reason, and I wanted to leave the possibility open to calculate the workload of a non-worker user, this is related to the paragraph above. I've commited a change to add a check anyway just now. But besides this, I can't really see anything missed. 

The userrolles endpoint has been removed. The reason for it supporting multiple assigned roles was simple, it was reusable if the project requirements changed to having multiple roles assigned, and there was no harm in doing so this way.. 

>If you are interested in the data you can just use the built-in SSOE.
It was more convinient for me, than using the debugging tools... I feel like this just causes more inconvinience, than what improvements this brings to the project.

2021-11-10 13:07 UTC, pop-simon requested changes
There are minor issues with the code and with the `Authorize` attributes but all in all it is nice work. 👏

2021-11-10 13:07 UTC, pop-simon commented on wman-backend/Wman.Logic/Classes/AuthLogic.cs
> +                await userManager.AddToRoleAsync(user, "Worker");
As you are adding a `Worker` please rename the method to something like `CreateWorker`. Also rename the method in the `AuthController` that calls this method.
Delete the commented out section in this method please.
**These are needed for clarity.**

2021-11-10 13:07 UTC, pop-simon commented on wman-backend/Wman.Logic/Classes/AuthLogic.cs
> +            var users = await this.userManager.GetUsersInRoleAsync(roleName);
Handle the case when the role does not exist. If it remains in that form the FE gets an empty list with 200 OK statuscode but does not get the information about the role not existing though it should.

2021-11-10 13:07 UTC, pop-simon commented on wman-backend/Wman.Logic/Classes/AuthLogic.cs
> +        private async Task<string> ValidateRolename(string input)
What is the purpose of this method?
You could use this method to validate the role in `Task<List<UserDTO>> GetAllUsersOfRole(string roleName)` method. If you do so, decide which implementation will be used. I prefer not to use the `switch-case` but **it is up to you**.

2021-11-10 13:07 UTC, pop-simon commented on wman-backend/Wman.Logic/Classes/EventLogic.cs
> +            if (await userManager.IsInRoleAsync(selectedUser, "Worker") == false)
**It is just an advice**: in an if statement you do not need to compare a boolean value. My suggestion looks clearer to me but it is my opinion.
```suggestion
            if (!await userManager.IsInRoleAsync(selectedUser, "Worker"))
```

2021-11-10 13:07 UTC, pop-simon commented on wman-backend/Wman.Logic/Classes/EventLogic.cs
> +                if (await userManager.IsInRoleAsync(selectedUser, "Worker") == false)
Same advice applies here.
```suggestion
                if (!await userManager.IsInRoleAsync(selectedUser, "Worker"))
```

2021-11-10 13:07 UTC, pop-simon commented on wman-backend/Wman.Logic/Classes/UserLogic.cs
> +                if (await userManager.IsInRoleAsync(selectedUser, "Worker") == false)
Same advice applies here too.
```suggestion
                if (!await userManager.IsInRoleAsync(selectedUser, "Worker"))
```

2021-11-10 13:07 UTC, pop-simon commented on wman-backend/Wman.WebAPI/Controllers/AuthController.cs
> +        //public async Task<ActionResult<IEnumerable<string>>> RolesOfUser(string username)
Remove the code that was commented out. This method will not be needed in the future because we use JWT and that can contain the roles as well.

2021-11-10 13:07 UTC, pop-simon commented on wman-backend/Wman.WebAPI/Controllers/CalendarEventController.cs
> +    [Authorize]
You should apply the following `Authorize` attribute in order not to repeat the code at every method. **After updating the attribute, remove the unneccesary attributes at the methods.**
```suggestion
    [Authorize(Roles = "Admin, Manager, Worker")]
```

2021-11-10 13:07 UTC, pop-simon commented on wman-backend/Wman.WebAPI/Controllers/EventController.cs
> +        [Authorize(Roles = "Admin, Manager")]
You should apply the `[Authorize(Roles = "Admin, Manager")]` attribute at line 19 in order not to repeat the code at every method. After updating the attribute, remove the unneccesary attributes at the methods.
***Furthermore, I am not sure the `Admin` should be able to access these features.***

2021-11-10 13:07 UTC, pop-simon commented on wman-backend/Wman.WebAPI/Controllers/LabelController.cs
> +        [Authorize(Roles = "Admin, Manager")]
You should apply the `[Authorize(Roles = "Admin, Manager")]` attribute at line 15 in order not to repeat the code at every method. After updating the attribute, remove the unneccesary attributes at the methods.
***Furthermore, I am not sure the `Admin` should be able to access these features.***

2021-11-10 13:07 UTC, pop-simon commented on wman-backend/Wman.WebAPI/Controllers/UserController.cs
> +        [Authorize(Roles = "Admin, Manager")]
You should apply the `[Authorize(Roles = "Admin, Manager")]` attribute at line 18 in order not to repeat the code at every method. After updating the attribute, remove the unneccesary attributes at the methods.

2021-11-10 16:01 UTC, luxz97 commented on wman-backend/Wman.Logic/Classes/EventLogic.cs
> +            if (await userManager.IsInRoleAsync(selectedUser, "Worker") == false)
Will keep in mind, to me the readability is just about the same on both.

2021-11-10 17:16 UTC, pop-simon approved these changes
Nice work thanks for the changes 👌

2021-11-11 13:49 UTC, tsaskater approved these changes

2021-11-11 20:35 UTC, merged