Feature/10 print events daily view
bprof-projm/wman pull request #55
Opened 2021-11-17 19:11 UTC by szdariusz

Preview and print functionality for events assigned to a specific user.

2021-11-18 21:50 UTC, tsaskater requested changes

2021-11-18 21:50 UTC, tsaskater commented on wman-frontend/src/components/Print-functionality/Print-events/print-events.component.jsx
> +        event => event.assignedUsers[0].username.includes(searched)
This only checks for the first element of the assigned users which means the printed document won't be present when choosing a secondly assigned user or anything beyond the first. pls fix 🎅🏻🤹🏿‍♂️

2021-11-19 20:17 UTC, tsaskater approved these changes
Works really good! Good Job!
I'm gonna approve it but pls commit one more thing.
When a worker has no assigned jobs please display it somehow, same with errors. At the moment it's just empty, there is no visual feedback. (Empty=No jobs for the day? error?-> I go the console/network, an average user will not get that far) 
IMO this improves the user experience, also it's easier for us to understand why there are no printable events.

2021-11-20 09:30 UTC, szdariusz commented
I did it

2021-11-20 18:13 UTC, tamas-lengyel approved these changes
Looks good, nice job!

2021-11-21 12:15 UTC, pop-simon approved these changes
It works well, good job! 👏

2021-11-21 12:18 UTC, merged