20 Load events to calendar for a specific worker
bprof-projm/wman pull request #57
Opened 2021-12-20 23:00 UTC by akosgdcsi

getting things done

2021-12-22 21:25 UTC, luxz97 approved these changes

2021-12-23 12:26 UTC, pop-simon requested changes
**There are several problems with the implementation.**
- You do not follow the DRY principles. The four method you just implemented are already exist. The only difference is that the existing methods do not use filtering by `username`.
- This feature enables a worker to get their `WorkEvent`s. It is not allowed to get another worker's `WorkEvent`s for the currently logged in worker.
---
**There are two ways to implement this feature in my opinion.**
- You could extend the already existing methods with user checking. 
For example the method `public async Task<List<WorkEventForWorkCardDTO>> GetCurrentDayEvents()` can be modified like this:
```csharp
public async Task<List<WorkEventForWorkCardDTO>> GetCurrentDayEvents(string username)
        {
            var user = await userManager.Users
                .Where(x => x.UserName == username)
                .SingleOrDefaultAsync();
            List<WorkEvent> events = await (from x in workEventRepo.GetAll()
                                            where x.EstimatedStartDate.DayOfYear == DateTime.UtcNow.DayOfYear && x.EstimatedStartDate.Year == DateTime.Today.Year
                                            select x).ToListAsync();

            if (await userManager.IsInRoleAsync(user, "worker"))
            {
                events = events.Where(x => x.AssignedUsers.Any(x => x.UserName == username)).ToList();
            }

            return mapper.Map<List<WorkEventForWorkCardDTO>>(events);
        }
```
In this case you have to modify the related **interface** and **controller** as well. Furthermore in `AuthLogic.cs` the `claims` starting at line 136 have to look like this:
```csharp
var claims = new List<Claim>
                {
                  new Claim(JwtRegisteredClaimNames.Sub, user.UserName),
                  new Claim(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString()),
                  new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                  new Claim(ClaimTypes.Name, user.UserName)
                };
```
- The other solution is to keep the new methods but those should use the existing ones and then filter the results.

In both solutions you should get the `username` from the `HttpContext` as Zoli did in the previous issue's implementation #56 in `WorkerController.cs`.

I am sure that there are other ways to fix this but only these two solutions came to my mind.

2021-12-23 12:26 UTC, pop-simon commented on wman-backend/Wman.Logic/Classes/CalendarEventLogic.cs
> +                          where x.EstimatedStartDate.DayOfYear >= firstDayOfTheWeek.DayOfYear && x.EstimatedStartDate.DayOfYear <= lastDayOfTheWeek.DayOfYear
The constraint is almost good but it shall contain something like this: `x.EstimatedStartDate.Year == DateTime.Today.Year`
**This error comes up in every method in this class so please fix all of them.**

2021-12-23 22:57 UTC, tsaskater requested changes
Works good. Very clever solution.
I need some refactoring. Please add a field as phoneNumber for the workers because it's missing at the moment.

2021-12-23 23:00 UTC, akosgdcsi commented
Time to ruin somebody's Xmas

2021-12-23 23:00 UTC, akosgdcsi commented
![kép](https://user-images.githubusercontent.com/74248920/147298035-1b2cce3d-993b-4cec-a407-cbb40d22c414.png)

2021-12-23 23:02 UTC, tsaskater commented
> Time to ruin somebodys Xmas

![image](https://media4.giphy.com/media/3XtJmVnsvdAJudsK0n/giphy.gif?cid=ecf05e47yxrqs6gjx5l85uhsf377t2yaaynoqpghflrdyk4r&rid=giphy.gif&ct=s)

2021-12-23 23:06 UTC, akosgdcsi commented
![image](https://user-images.githubusercontent.com/74248920/147298262-3ae484be-6282-4c90-bea7-190ec21afe28.jpeg)

Me vibing right now

2021-12-23 23:09 UTC, rolandbogdan commented
![orban-viktor-1](https://user-images.githubusercontent.com/74932478/147298428-7089b876-f202-4baa-a06e-0f563fd2eabb.jpg)
Me seeing that I got added as a reviewer to another WMAN PR...

2021-12-24 23:29 UTC, tsaskater approved these changes
![image](https://media3.giphy.com/media/ABPYR9xUWHPsBH9A6y/giphy.gif?cid=ecf05e4791xplg1tbmlfsht2slxjkl0c8ouauff3dewv47tq&rid=giphy.gif&ct=g)
🎄🤶🏿

2021-12-26 18:38 UTC, pop-simon approved these changes

2021-12-26 18:39 UTC, merged