Feature/28 workforce management from the admin u
bprof-projm/wman pull request #59
Opened 2021-12-26 23:33 UTC by luxz97

2021-12-28 17:28 UTC, pop-simon requested changes
The code looks good but I think the Admin should be able to add, modify and remove Managers as well as Workers. Please implement the `CreateManager`, `ModifyManager` and `DeleteManager` endpoints too because they are also included as workforce.

Besides these it is a good job! 👌

2021-12-28 17:28 UTC, pop-simon commented on wman-backend/Wman.WebAPI/Controllers/AuthController.cs
> +        public async Task<ActionResult> FirstTimeSetup([FromForm] RegisterDTO model)
I think this endpoint creates a vulnerability. Furthermore it is not a necessary endpoint so please remove it and also the related method in the logic layer.

2021-12-29 23:11 UTC, tsaskater approved these changes
IMO workforce management should contain, managers too.
Other than that, good Job.
(Some params in dtos should be required, but thats an all around refactoring issue...)

2021-12-30 09:53 UTC, pop-simon approved these changes

2021-12-30 09:54 UTC, merged