photo and status stuff
bprof-projm/wman pull request #69
Opened 2022-01-02 22:03 UTC by akosgdcsi

i dont know if its works for you guys, because gitkraken doin some  interesting stuff

2022-01-03 21:42 UTC, tsaskater requested changes
Remove the todo pls... 😠🙅🏿‍♀️
Otherwise I love it.

2022-01-03 21:42 UTC, tsaskater commented on wman-backend/Wman.Logic/Classes/EventLogic.cs
> +            // TODO: Innentől átadni.
Please remove this unnecessary  TODO as it's not a todo.
Otherwise good job. Works as intended.

2022-01-04 18:49 UTC, tsaskater approved these changes
You haven’t missed a thing.

2022-01-05 17:24 UTC, pop-simon requested changes
Well done, but small changes required 👌

2022-01-05 17:24 UTC, pop-simon commented on wman-backend/Wman.Logic/Classes/EventLogic.cs
> +            }
Do not use both `if-else` and `switch-case` though you can use an `if` in a `case`. If you choose `switch-case` the default case should throw an `Exception` like `Status not found`.

2022-01-06 19:50 UTC, akosgdcsi commented
If somehow the code gets to the default case, 10000 puppies shall rot in hell

2022-01-06 19:59 UTC, akosgdcsi commented
![kép](https://user-images.githubusercontent.com/74248920/148443660-80c7cc86-6c80-4625-9082-c38025cfdc0e.png)

2022-01-07 09:03 UTC, pop-simon approved these changes
That is not what I meant but nevermind

2022-01-07 09:13 UTC, merged