Feature/21 create the main calendar view for a worker
bprof-projm/wman pull request #71
Opened 2022-01-03 21:08 UTC by szdariusz

- main view for workers 
- fix print view  => button instead ctrl+p
- login navigate the user to his correct view based on his role

2022-01-03 21:32 UTC, tsaskater approved these changes
Very nice work!
Works as intended.

PS:
IMO later on we should install some kind of date formatter. (for example [react-moment](https://www.npmjs.com/package/react-moment))
We could format the dates as `yyyy.MM.dd. H:m` and it would look better.

2022-01-04 13:32 UTC, szdariusz commented
Dates formatted 😄

2022-01-04 16:05 UTC, pop-simon requested changes
Everything looks good, only the date format needs a little change.
**Nice job!** 👌

2022-01-04 16:05 UTC, pop-simon commented on wman-frontend/src/components/Worker-page/one-day-event/one-day-events.component.jsx
> +                        <th> <Moment format="YYYY.MM.DD. HH:MM">{event.event.estimatedFinishDate}</Moment></th>
The minutes component should be lower case in order to display the minutes instead of the month. This applies to the code at line 27 too.
```suggestion
                        <th> <Moment format="YYYY.MM.DD. HH:mm">{event.event.estimatedFinishDate}</Moment></th>
```

2022-01-04 17:15 UTC, pop-simon approved these changes

2022-01-04 17:19 UTC, tamas-lengyel approved these changes
Looks good, nice job!

2022-01-04 17:19 UTC, merged

2022-01-04 18:48 UTC, tsaskater approved these changes