Feature/82 feedback for managers xlsx generation
bprof-projm/wman pull request #88
Opened 2022-03-22 16:18 UTC by luxz97

appsettings.json:
"OutputDir": "XLS_DIRECTORY_PATH"

2022-03-22 16:26 UTC, luxz97 commented
Both related endpoints are temporary, until scheduled xls sending is implemented, so file access/security was not a concern at this time.

2022-03-26 14:07 UTC, tsaskater approved these changes
looks good 🍉

2022-03-27 08:49 UTC, pop-simon requested changes
Good job I like how you handled the Excel generation however there is a tiny issue with sending the email. 🤞

2022-03-27 08:49 UTC, pop-simon commented on wman-backend/Wman.Logic/Services/EmailService.cs
> +                Attachment data = new Attachment(filePath, MediaTypeNames.Application.Octet);
A resource is created here that is not handled after sending the email (at line 88). This causes that the Excel generation cannot be done again unless the application is restarted.
Please add the following (or something that does the same) after line 88:
```c#
if (mail.Attachments.Count > 0)
{
    foreach (var attachment in mail.Attachments)
    {
        attachment.Dispose();
    }
}
```

2022-03-27 10:33 UTC, pop-simon approved these changes

2022-03-27 10:34 UTC, merged