Feature/84 UI experience
bprof-projm/wman pull request #91
Opened 2022-04-19 20:17 UTC by tamas-lengyel

2022-04-23 09:49 UTC, tsaskater requested changes
Marked the story as `under negotiation`.
We need to change the texts before it's done.
Otherwise, very nice! 👍🛶

2022-05-13 10:27 UTC, pop-simon approved these changes
Everything looks good! I think the code is approveable despite the texts should be updated. Good job 🏆

2022-05-17 17:01 UTC, pop-simon approved these changes

2022-05-17 17:02 UTC, tsaskater approved these changes
Very text! 💬👁‍🗨

2022-05-17 17:03 UTC, merged